version: "3.8"

services:
  vault:
    image: kalpak44/vault-docker-bootstrap:latest
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_API_ADDR: "http://192.168.1.50:8200"
      VAULT_CLUSTER_ADDR: "http://192.168.1.50:8201"
    volumes:
      - ./vault-data:/vault/data
      - ./vault-file:/vault/file
